import { Geist, Geist_Mono, Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/AppContext.js";
import FindJobProvider from "./context/FindJob";
import SidebarMobile from "./components/SidebarMobile"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  weight: ["400", "700"], // Specify weights you want to use
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
      >
        <FindJobProvider>
          <AppProvider>
            <SidebarMobile/>
            {children}
            </AppProvider>
        </FindJobProvider>
      </body>
    </html>
  );
}
